version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: sh ./docker-entrypoint.sh
    environment:
      PORT: 8080
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    ports:
      - '3000:8080'
    volumes:
      - '.:/myapp'

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/myapp'
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"


volumes:
  redis:
  db: