version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    depends_on:
      - 'db'
      - 'redis'
      - 'sidekiq'
    build: .
    command: sh ./docker-entrypoint.sh
    environment:
      PORT: 8080
    ports:
      - '3000:8080'
    volumes:
      - '.:/myapp'

  redis:
    image: redis
    volumes:
      - ../../tmp/db:/var/lib/redis/data
  sidekiq:
    build: .
    command: 'bundle exec sidekiq'
    volumes:
      - ./:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - redis

volumes:
  redis:
  db: